version: "3.8"

services:
  pg-balenstore:
    image: postgres:14.1-alpine
    container_name: postgres_balenstore
    environment:
      POSTGRES_DB: balenstore_db
      POSTGRES_USER: balen
      POSTGRES_PASSWORD: balen
    ports:
      - 5432:5432
    volumes:
      - pg-balenstore-data:/var/lib/postgresql/data

volumes:
  pg-balenstore-data:
    driver: local
